### ISSUE TITLE
Error: Non-null vaule "yURL was null

### ISSUE THREAD

**Issue by jennparker** [jennparker/TasteDive-Test-Drive#9]
Process: com.booisajerk.tastedivetester, PID: 25780
    com.squareup.moshi.JsonDataException: Non-null value 'yUrl' was null at $.Similar.Results[4].yUrl
        at com.booisajerk.tastedivetester.models.ResultJsonAdapter.fromJson(ResultJsonAdapter.kt:36)
        at com.booisajerk.tastedivetester.models.ResultJsonAdapter.fromJson(ResultJsonAdapter.kt:12)
        at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
        at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
        at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
        at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
        at com.booisajerk.tastedivetester.models.SimilarJsonAdapter.fromJson(SimilarJsonAdapter.kt:32)
        at com.booisajerk.tastedivetester.models.SimilarJsonAdapter.fromJson(SimilarJsonAdapter.kt:14)
        at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
        at com.booisajerk.tastedivetester.models.ResponseDataJsonAdapter.fromJson(ResponseDataJsonAdapter.kt:25)
        at com.booisajerk.tastedivetester.models.ResponseDataJsonAdapter.fromJson(ResponseDataJsonAdapter.kt:12)
        at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
        at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:41)
        at com.booisajerk.tastedivetester.SearchResultActivity$requestMovies$request$1.onResponse(SearchResultActivity.kt:73)
        at com.booisajerk.tastedivetester.SearchResultActivity$requestMovies$request$1.onResponse(SearchResultActivity.kt:18)
        at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:82)
        at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:29)
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by jennparker** [comment]
fixed
